In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
import matplotlib.pyplot as plt
!jupyter nbextension enable --py gmaps
!jupyter nbextension enable --py widgetsnbextension

# Import the API key.
from config import g_key

Enabling notebook extension jupyter-gmaps/extension...
      - Validating: ok
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: ok

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Ushuaia,AR,2021-05-27 02:27:38,-54.8000,-68.3000,29.86,86,75,18.41
1,1,Lucea,JM,2021-05-27 02:29:54,18.4510,-78.1736,80.46,83,65,12.71
2,2,Mehamn,NO,2021-05-27 02:29:55,71.0357,27.8492,39.54,73,86,12.64
3,3,Puerto Del Rosario,ES,2021-05-27 02:26:04,28.5004,-13.8627,64.15,68,21,9.22
4,4,Hermanus,ZA,2021-05-27 02:27:52,-34.4187,19.2345,55.90,73,100,5.06

In [3]:
# Get the data types
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [5]:
# 1. Assign the locations to an array of latitude and longitude pairs.
#locations = [latitude, longitude]
# 2. Assign the weights variable to some values.
#temperatures = # an array of length equal to the locations array length
# 3. Assign the figure variable to the gmaps.figure() attribute.
#fig = gmaps.figure()
# 4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations.
#heatmap_layer = gmaps.heatmap_layer(locations, weights=temperatures)
# 5. Add the heatmap layer.
#fig.add_layer(heatmap_layer)
# 6. Call the figure to plot the data.
#fig

In [6]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0,31.0),zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp,0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of Wind Speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [18]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

What is the minimum temperature you would like for your trip? 20
What is the maximum temperature you would like for your trip? 95

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Ushuaia,AR,2021-05-27 02:27:38,-54.8000,-68.3000,29.86,86,75,18.41
1,1,Lucea,JM,2021-05-27 02:29:54,18.4510,-78.1736,80.46,83,65,12.71
2,2,Mehamn,NO,2021-05-27 02:29:55,71.0357,27.8492,39.54,73,86,12.64
3,3,Puerto Del Rosario,ES,2021-05-27 02:26:04,28.5004,-13.8627,64.15,68,21,9.22
4,4,Hermanus,ZA,2021-05-27 02:27:52,-34.4187,19.2345,55.90,73,100,5.06
5,5,Rikitea,PF,2021-05-27 02:29:55,-23.1203,-134.9692,74.70,70,91,17.31
6,6,Betsiamites,CA,2021-05-27 02:29:55,48.9413,-68.6460,57.60,87,100,13.67
7,7,Nikolskoye,RU,2021-05-27 02:29:56,59.7035,30.7861,47.79,98,91,4.70
8,8,Saint-Philippe,RE,2021-05-27 02:29:56,-21.3585,55.7679,69.39,83,19,2.21
9,9,Hithadhoo,MV,2021-05-27 02:28:05,-0.6000,73.0833,84.09,68,76,19.62

In [19]:
preferred_cities_df.isnull().sum()

City_ID       0
City          0
Country       6
Date          0
Lat           0
Lng           0
Max Temp      0
Humidity      0
Cloudiness    0
Wind Speed    0
dtype: int64

In [20]:
#Create new dataframe for hotel info
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
#Add new column for hotel name
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

                 City Country  Max Temp      Lat       Lng Hotel Name
0             Ushuaia      AR     29.86 -54.8000  -68.3000
1               Lucea      JM     80.46  18.4510  -78.1736
2              Mehamn      NO     39.54  71.0357   27.8492
3  Puerto Del Rosario      ES     64.15  28.5004  -13.8627
4            Hermanus      ZA     55.90 -34.4187   19.2345
5             Rikitea      PF     74.70 -23.1203 -134.9692
6         Betsiamites      CA     57.60  48.9413  -68.6460
7          Nikolskoye      RU     47.79  59.7035   30.7861
8      Saint-Philippe      RE     69.39 -21.3585   55.7679
9           Hithadhoo      MV     84.09  -0.6000   73.0833

In [21]:
# Create base URL
base_url='https://maps.googleapis.com/maps/api/place/nearbysearch/json'

# Set parameters to search for a hotel.
params = {"radius": 5000,
          "type": "lodging",
          "key": g_key}

# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"
    
    # Make request and get the JSON data from the search
    hotels = requests.get(base_url, params=params).json()
    
    # Grab the first hotel from the results and store the name
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found....skipping")

Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping
Hotel not found....skipping

In [22]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Ushuaia,AR,29.86,-54.8000,-68.3000,Albatros Hotel
1,Lucea,JM,80.46,18.4510,-78.1736,Grand Palladium Jamaica Resort & Spa
2,Mehamn,NO,39.54,71.0357,27.8492,Mehamn Arctic Hotel AS
3,Puerto Del Rosario,ES,64.15,28.5004,-13.8627,Hotel JM Puerto del Rosario
4,Hermanus,ZA,55.90,-34.4187,19.2345,Misty Waves Boutique Hotel
5,Rikitea,PF,74.70,-23.1203,-134.9692,Pension Maro'i
6,Betsiamites,CA,57.60,48.9413,-68.6460,
7,Nikolskoye,RU,47.79,59.7035,30.7861,Tourist House - Sablino
8,Saint-Philippe,RE,69.39,-21.3585,55.7679,"Chambres d'hôte ""La Trinité"""
9,Hithadhoo,MV,84.09,-0.6000,73.0833,Scoop Guest House

In [25]:
# Add pop-up marker for each city to display hotel name, city name, country, and max temp
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations,info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))